import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'HU Career City',
  description: 'Generated by create next app',
  openGraph: {
    images: '/HU-Logo.png',
  },
  twitter: {
    images: ['/HU-Logo.png'],
    card: 'summary_large_image',
  },
  icons: {
    icon: '/favicon-optimized.png',
    shortcut: '/favicon-optimized.png',
    apple: '/favicon-optimized.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
